config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  devise_for :users, controllers: { sessions: 'trestle/auth/sessions' }

  namespace :orders do
    resources :create_new_order, only: %i[create]
  end
  namespace :api do
    resources :items
  end

  namespace :api do
    namespace :v1 do
      resources :customers
    end
  end

  resources :items
  resources :customers, only: %w[index show new create]
  resources :contacts, only: %w[index show new create]
  resources :orders, only: %w[index show new]
  resources :fabrics, only: %w[index new create]

  resources :cards, only: %i[index show] do
    member do
      get 'trello', to: 'cards#trello'
      get 'wicked_pdf', to: 'cards#wicked_pdf'
      get 'image', to: 'cards#image'
    end
  end

  namespace :payments do
    resources :yoo_kassa, only: %i[index create]
  end

  post '/webhooks/trello/*path', to: 'webhooks/trello#create', via: :all
  get '/webhooks/trello/*path', to: 'webhooks/trello#index', via: :all

  resources :tracking, only: %i[show]

  root to: 'items#index'
end

app/controllers/tracking_controller.rb
# frozen_string_literal: true

# class TrackingController
class TrackingController < ApplicationController
  skip_before_action :authenticate_user!

  def show
    @order = Order.find_by(trello_card_id: params[:id])

    render layout: false
  end
end

app/views/tracking/_measurements.html.erb
<div class='card-body'>
  <%- @order.product.product_measurements.each do |measurement| %>
    <div>
      <%= measurement.measure.name %> ориентировочный диапазон <%= measurement.range %>
    </div>
  <% end %>
</div>

app/views/tracking/show.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
<meta name="viewport" content="width=device-width, initial-scale=1">

<div class="container">
  <div class='card m-4'>
    <div class='card-header'>
      <div class='d-flex flex-row justify-content-between'>
        <p>
          Заказ
          <%=
            if user_signed_in?
              link_to @order.idx, OrdersAdmin.path(:show, id: @order), target: '_blank'
            else
              @order.idx
            end
          %>
        </p>
        <%=
          if user_signed_in?
            link_to 'trello ↗', @order.trello_url, target: '_blank', class: 'btn btn-primary'
          end
        %>
      </div>
    </div>

    <div class='card-body'>

      <p>
        <strong>заказчик:</strong>
        <%=
          if user_signed_in?
            link_to @order.customer.name, customer_path(@order.customer)
          else
            @order.customer.name
          end
        %>
      </p>

      <div>
        <p>
        <strong>изделие:</strong>
        <%= @order.product.name %>
        </p>
        <%=
          if @order.product.illustration.attached?
            image_tag(@order.product.illustration, class: 'img-fluid')
          end
        %>
      </div>

      <div>

        <strong>ткань:</strong>
        <p>
          <%= @order.fabric.title %>
          <%= @order.fabric.description %>
          <%= @order.fabric.material %>
        </p>
        <%=
          if @order.fabric.illustration.attached?
            image_tag(@order.fabric.illustration, class: 'img-fluid')
          end
        %>
      </div>

      <p>
        <strong>комментарий:</strong>
        <%= @order.comment %>
      </p>

      <p>
        <strong>заказ от:</strong>
        <%= @order.created_at %>
      </p>

      <p>
        <strong>заметки:</strong>
        <%= @order.notes %>
      </p>
    </div>

    <%= render partial: 'measurements', locals: { order: @order } %>

    <div class='card-footer bg-info text-white'>

      <%= render 'orders/events', order: @order %>

      <%- Order.order(created_at: :desc).where(customer_id: @order.customer_id).each do |order| %>
        <div class='mt-4'>
          <%= order.idx %>
          <%=
            order.trello_card_id &&
              link_to(
                [order.product.name, order.fabric.title].join(' - '),
                tracking_path(order.trello_card_id))
          %>
        </div>
      <% end %>
    </div>
  </div>
</div>