config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  devise_for :users, controllers: { sessions: 'trestle/auth/sessions' }

  namespace :orders do
    resources :create_new_order, only: %i[create]
  end
  namespace :api do
    resources :items
  end

  namespace :api do
    namespace :v1 do
      resources :customers
    end
  end

  resources :items
  resources :customers, only: %w[index show new create]
  resources :contacts, only: %w[index show new create]
  resources :orders, only: %w[index show new]
  resources :fabrics, only: %w[index new create]

  resources :cards, only: %i[index show] do
    member do
      get 'trello', to: 'cards#trello'
      get 'wicked_pdf', to: 'cards#wicked_pdf'
      get 'image', to: 'cards#image'
    end
  end

  namespace :payments do
    resources :yoo_kassa, only: %i[index create]
  end

  post '/webhooks/trello/*path', to: 'webhooks/trello#create', via: :all
  get '/webhooks/trello/*path', to: 'webhooks/trello#index', via: :all

  resources :tracking, only: %i[show]

  root to: 'items#index'
end

app/controllers/payments/yoo_kassa_controller.rb
# frozen_string_literal: true

module Payments
  # class Payments::YooKassaController
  class YooKassaController < ApplicationController
    after_action :attach_event_to_order, only: %i[create]

    PAYMENT_INTENT = 'payment_intent_yookassa'

    # creates a payment intent and hooks it to the order
    def create
      payment_intent = Yookassa.payments.create(payment:)

      @confirmation_url = payment_intent.confirmation.confirmation_url
    end

    # Yookassa checks this method to see if the payment url is valid
    def index; end

    private

    def attach_event_to_order
      order = Order.find_by(idx: params[:order])

      return unless order

      order.order_events.create(
        event_source: PAYMENT_INTENT,
        event_data: { payment_intent: }
      )
    end

    def payment # rubocop:disable Metrics/MethodLength
      {
        amount: {
          value:,
          currency: 'RUB'
        },
        capture: true,
        description: "Заказ № #{order}",
        receipt: {
          customer: {
            full_name:,
            email:,
            phone:
          },
          items: [
            {
              description:,
              quantity: '1.00',
              amount: {
                value:,
                currency: 'RUB'
              },
              vat_code: 1,
              payment_mode: 'full_prepayment',
              payment_subject: 'service',
              country_of_origin_code: 'RU'
            }
          ]
        },
        expires_at:,
        confirmation: {
          type: 'redirect',
          return_url:
        }
      }
    end

    def full_name
      params[:full_name]
    end

    def product
      params[:product]
    end

    def fabric
      params[:fabric]
    end

    def order
      params[:order]
    end

    def email
      params[:email]
    end

    def phone
      params[:phone]
    end

    def description
      ['Изготовление на заказ:', product, fabric].join(' ')
    end

    def value
      params[:amount]
    end

    def return_url
      'https://unicollezione.com'
    end

    def expires_at
      if params[:expires_at].present?
        Time.parse(params[:expires_at])
      else
        Time.now + 2.hour
      end
    end
  end
end

app/views/payments/yoo_kassa/create.html.erb
<div>
  <%= turbo_frame_tag 'yookassa' do %>
    <div
      data-controller="clipboard"
      data-clipboard-success-content="готово!"
      class="input-group mb-3 pr-2"
    >
      <input
          type="text"
          value="<%= @confirmation_url %>"
          data-clipboard-target="source"
          class='form-control'
          type='text'
      >
      <div class="input-group-append">
        <button
          type="button"
          data-action="clipboard#copy"
          data-clipboard-target="button"
          class='btn btn-outline-secondary'
        >
          скопировать
        </button>
      </div>
    </div>
  <% end %>
</div>

app/views/payments/yoo_kassa/index.html.erb
<div>
  <%= turbo_frame_tag 'yookassa' do %>

    <div data-controller="yookassa">
      <%= form_with model: @order, url: payments_yoo_kassa_index_path, data: { controller: 'payments/yookassa' } do |f| %>
        <div class="form-group">
          <div class="my-2" data-controller='yookassa'>
            <%=
              f.phone_field :phone,
                label: false,
                placeholder: 'Номер телефона',
                class: 'form-control',
                data: { controller: 'yookassa', action: "change->yookassa#phone" }
              %>
          </div>

          <div class="my-2" data-controller='yookassa'>
            <%=
              f.text_field :email,
                label: false,
                placeholder: 'Email',
                class: 'form-control',
                data: { controller: 'yookassa', action: "change->yookassa#email" }
              %>
          </div>
        </div>

        <div class='input-group mb-3 mr-2' data-controller='yookassa'>
          <%= f.hidden_field :full_name %>
          <%= f.hidden_field :product %>
          <%= f.hidden_field :fabric %>
          <%= f.hidden_field :order %>

          <%=
            f.number_field :amount,
              label: false,
              placeholder: 'Сумма платежа',
              class: 'form-control',
              data: { controller: 'yookassa', action: "change->yookassa#validate" }
          %>


          <div class='input-group-append'>
            <%= f.submit 'ссылка', class: 'btn', disabled: true %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>