config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  devise_for :users, controllers: { sessions: 'trestle/auth/sessions' }

  namespace :orders do
    resources :create_new_order, only: %i[create]
  end
  namespace :api do
    resources :items
  end

  namespace :api do
    namespace :v1 do
      resources :customers
    end
  end

  resources :items
  resources :customers, only: %w[index show new create]
  resources :contacts, only: %w[index show new create]
  resources :orders, only: %w[index show new]
  resources :fabrics, only: %w[index new create]

  resources :cards, only: %i[index show] do
    member do
      get 'trello', to: 'cards#trello'
      get 'wicked_pdf', to: 'cards#wicked_pdf'
      get 'image', to: 'cards#image'
    end
  end

  namespace :payments do
    resources :yoo_kassa, only: %i[index create]
  end

  post '/webhooks/trello/*path', to: 'webhooks/trello#create', via: :all
  get '/webhooks/trello/*path', to: 'webhooks/trello#index', via: :all

  resources :tracking, only: %i[show]

  root to: 'items#index'
end

app/models/customer.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: customers
#
#  id         :bigint           not null, primary key
#  idx        :integer
#  nickname   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Customer < ApplicationRecord
  validates :nickname, presence: true
  has_many :orders
  has_many :products
  has_many :contacts, dependent: :destroy
  has_many :addresses, dependent: :destroy

  def name
    nickname
  end
end

app/controllers/customers_controller.rb
# frozen_string_literal: true

# class CustomersController
#
# CRUD for customers
class CustomersController < ApplicationController
  before_action :customers, only: %i[index create]
  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)

    redirect_to customer_path(@customer) if @customer.save
  end

  def index
    if params[:search].present?
      @customers = Customer.where('nickname LIKE ?', "%#{params[:search]}%")
    else
      @customers = Customer.last(10)
    end
  end

  def show
    @customer = Customer.find(params[:id])
  end

  private

  def customer_params
    params.require(:customer).permit(:nickname)
  end

  def customers
    @customers ||= Customer.all
  end
end

app/views/customers/_customer.html.erb
<%= turbo_frame_tag 'customers' do %>
  <%= form_for @customer, data: { turbo_frame: 'customers' } do |f| %>
    <div class='d-flex justify-content-between'>
      <label>добавить покупателя</label>
      <%= link_to 'X', customers_path, class: 'btn btn-outlinedanger pull-right', data: { turbo_frame: 'customers' } %>
    </div>
    <div class='form form-group'>
      <div class='form-row mb-2'>
        <div class='col'>
          <%= f.label :name %>
          <%= f.text_field :nickname, class: 'form-control' %>
        </div>
      </div>
      <div class='form-row'>
        <div class='col'>
          <%= f.submit class: 'btn btn-outline-primary form-control'%>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/customers/_select.html.erb
<%= turbo_frame_tag 'customers' do %>
  <%= select_tag :customer_id, options_from_collection_for_select(
    @customers, :id, :nickname, { prompt: 'Select a customer' }
  ),
  class: 'form-control',
  'data-controller': 'orders',
  'data-orders-target': 'customer'
%>
<% end %>

app/views/customers/create.html.erb
<h1>Customers#create</h1>
<p>Find me in app/views/customers/create.html.erb</p>

app/views/customers/index.html.erb
<%= render partial: 'orders/customers', locals: { customer: @customer } %>

<%= form_tag customers_path, method: :get do %>
  <div class='d-flex flex-row justify-content-between'>
    <div class='flex-grow-1 mb-2'>
      <%= text_field_tag :search, params[:search], placeholder: "Search", class: 'form-control' %>
    </div>
    <div class='mb-2'>
      <%= submit_tag "Search", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

<table class='table table-striped table-responsible'>
<tbody>
  <th>#</th>
  <th>ник</th>
  <th>профиль</th>
  <%- @customers.each do |customer| %>
    <tr>
      <td><%= customer.id %></td>
      <td><%= customer.nickname %></td>
      <td><%= link_to 'Show', customer %></td>
    </tr>
  <% end %>
</tbody>
</table>

app/views/customers/new.html.erb
<%= turbo_frame_tag 'customers' do %>
  <%= render partial: 'customer' %>
<% end %>

app/views/customers/show.html.erb
<%= turbo_frame_tag 'customers' do %>
  <div class='card'>
    <div class='card-header d-flex flex-row justify-content-between'>
      <h4 class='card-title'>
        <%= @customer.nickname %>
      </h4>
      <%= link_to 'Edit', CustomersAdmin.path(:show, id: @customer.id), class: 'btn btn-primary' %>
    </div>

    <div class='card-body'>
      <div class='mt-4'>
        <label>
          Контакты
          <%= @customer.contacts.size %>
          <%= turbo_frame_tag 'contacts' do %>

            <%= link_to '+', new_contact_path(customer_id: @customer), class: 'btn btn-outline-info' %>

            <%- @customer.contacts.each do |contact| -%>
              <div class='row'>
                <span>
                  <%= contact.name %>
                  <%= link_to contact.value, contact.value, target: '_blank' %>
                </span>
              </div>
            <% end %>
          <% end %>
        </label>

      </div>

      <div class='mt-4'>
        <label>
          Адреса
          <%= @customer.addresses.size %>
        </label>

        <%- @customer.addresses.each do |address| -%>
          <div class='col-12'>
            <div class='row'>
              <div class='col-6'>
                <%= address.address_type.name %>
              </div>
              <div class='col-6'>
                <%= address.value %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <div class='card-footer d-flex flex-row'>
      <%= link_to 'закрыть', customers_path, class: 'btn btn-outline-secondary fload-right' %>
    </div>
  </div>
<% end %>