config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  devise_for :users, controllers: { sessions: 'trestle/auth/sessions' }

  namespace :orders do
    resources :create_new_order, only: %i[create]
  end
  namespace :api do
    resources :items
  end

  namespace :api do
    namespace :v1 do
      resources :customers
    end
  end

  resources :items
  resources :customers, only: %w[index show new create]
  resources :contacts, only: %w[index show new create]
  resources :orders, only: %w[index show new]
  resources :fabrics, only: %w[index new create]

  resources :cards, only: %i[index show] do
    member do
      get 'trello', to: 'cards#trello'
      get 'wicked_pdf', to: 'cards#wicked_pdf'
      get 'image', to: 'cards#image'
    end
  end

  namespace :payments do
    resources :yoo_kassa, only: %i[index create]
  end

  post '/webhooks/trello/*path', to: 'webhooks/trello#create', via: :all
  get '/webhooks/trello/*path', to: 'webhooks/trello#index', via: :all

  resources :tracking, only: %i[show]

  root to: 'items#index'
end

app/controllers/cards_controller.rb
# frozen_string_literal: true

# CardsController
# Render cards
class CardsController < ApplicationController
  layout false, only: [:image]

  before_action :card, only: %i[show trello image file_path]

  def index
    @cards = Order.where(prepared_at: nil).last(12)
  end

  def show
    render  pdf: @card.idx.to_s,
            margin: { top: 1, bottom: 1, left: 1, right: 1 },
            viewport_size: '1920x1080',
            encoding: 'utf8',
            page_size: 'A5',
            orientation: 'landscape',
            layout: 'pdf'
  end

  def trello
    render  pdf: @card.idx.to_s,
            margin: { top: 1, bottom: 1, left: 1, right: 1 },
            encoding: 'utf8',
            page_size: 'A4',
            layout: 'pdf',
            template: 'cards/trello'
  end

  def wicked_pdf
    render  pdf: @card.idx.to_s,
            margin: { top: 1, bottom: 1, left: 1, right: 1 },
            encoding: 'utf8',
            page_size: 'A4',
            layout: 'pdf',
            template: 'cards/wicked_pdf'
  end

  def image
    Trello::CreateOrderService.new(@card).generate_jpg unless @card.illustration.attached?
  end

  private

  def card
    @card ||= Order
              .includes(product: %i[product_measurements measures])
              .find_by(idx: params[:id])
  end
end

app/helpers/cards_helper.rb
module CardsHelper
  def notes_for(card)
    card.notes.gsub(/\n/, '<br/>').html_safe
  end
end

app/views/cards/image.html.erb
<%= image_tag @card.illustration %>

app/views/cards/index.html.erb
<div class='container'>
  <% @cards.each do |card| %>
    <div class='mt-2'>
      заказ
      <%= link_to card.idx, OrdersAdmin.path(:show, id: card.id) %>
      <%= link_to 'pdf', card_path(card.idx || card.id), target: '_blank' %>
    </div>
  <% end %>
</div>

app/views/cards/show.html.erb
<style>
table, th, td {
  border-collapse: collapse;
  vertical-align: baseline;
  text-align: left;
  vertical-align: top;
  text-align-last: justify;
}
th, td {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 8px;
  padding-right: 8px;
  vertical-align: baseline;
  text-align: left;
  vertical-align: top;
}
</style>

<div>
  <table style='width: 1024px; width: 100%;'>
    <tr style='height: 24px; width: 100%;'>
      <th style='width: 340px;'>
        <div>
          <div style='flex-direction: row' >
            <h2><%= "##{@card.idx}" %></h2>
            <%= "#{@card.ready_at&.strftime('%F')}" %>
          </div>
        </div>
      </th>
      <th style='width: 140px;'>
        <strong>
          <%= "#{@card.product.name}" %>
        </strong>
      </th>
      <th style='width: 320px;'>
        <div>
          <h2>
            <%= "#{@card.customer.nickname}" %>
          </h2>
        </div>
      </th>
      <th style='padding: 0px'>
      </th>
    </tr>

    <tr style='width: 100%; max-height: 640px;'>
      <td>
        <div>
          <div>
            <h2>
              <%= "#{@card.comment}"%>
            </h2>
          </div>
          <%= image_tag(@card.product.illustration, size: '240x320', class: 'img img-fluid')  if @card.product.illustration.present? %>
          <div>
            <%= "Ткань: #{@card.fabric.title}" %>
            <p>
              <%= @card.fabric.title%>
            </p>
            <p>
              <%= @card.fabric.material %>
            </p>
            <p>
              <%= @card.fabric.description %>
            </p>
          </div>
        </div>
      </td>

      <td>
        <div>
          <%= image_tag(@card.fabric.illustration, size: '120x160') if @card.fabric.illustration.present? %>
          <div>
            <strong>мерки клиента</strong>
            <strong>
              <%= notes_for(@card) %>
            </strong>
            <% @card.order_measures.each do |order_measure| %>
              <div>
                <%= "#{[order_measure.measure.tag, ":", order_measure.value].join}" %>
              </div>
            <% end%>
          </div>
        </div>
      </td>

      <td>
        <div>
          <p>полностью оплачен:
            <%= "#{@card.payed ? 'да' : 'нет'} "%>
          </p>
          <p>предоплата:
            <%= "#{@card.prepayment} "%>
          </p>
          <p>оплата:
            <%= "#{@card.payment} "%>
          </p>
        </div>
        <div>
          <p>куплен
            <%= "#{@card.purchased_at&.strftime('%F')}" %>
          </p>
          <p>готов к
            <%= "#{@card.ready_at&.strftime('%F')}" %>
          </p>
          <p>отправлен
            <%= "#{@card.prepared_at&.strftime('%F')}" %>
          </p>
        </div>
        <div style='text-align: bottom;'>
          <div>
            <p>Укомплектовал __________________</p>
          </div>
          <div>
            <p>Крой      ______________________</p>
          </div>
          <div>
            <p>Пошив    ______________________</p>
          </div>
          <div>
            <p>Проверил ______________________</p>
          </div>

          <% @card.product.instructions.each do |instruction| %>
            <strong>
              <%= "#{instruction.title}" %>
            </strong>
            <div>
              <%= "#{instruction.body}"%>
            </div>
          <% end %>
        </div>
      </td>

      <td style='text-align: center;'>
        <p>trello</p>
          <%= image_tag @card.trello_qr_code_url %>
        <p>card</p>
        <%= image_tag @card.qr_code_url %>
      </td>
    </tr>
  </table>
</div>

app/views/cards/trello.html.erb
<style>
table, th, td {
  border-collapse: collapse;
  vertical-align: baseline;
  text-align: left;
  vertical-align: top;
  text-align-last: justify;
}
th, td {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 8px;
  padding-right: 8px;
  vertical-align: baseline;
  text-align: left;
  vertical-align: top;
}
</style>

<div>
  <table style='width: 980px; height: 1080px; width: 100%;'>
    <tr style='height: 24px; width: 100%;'>
      <th>
        <div>
          <div style='flex-direction: row' >
            <h2>
              <%= "##{@card.idx}" %>
              <%= "#{@card.customer.nickname}" %>
            </h2>
          </div>
        </div>
      </th>
      <th>
        <h1>
          <%= "#{@card.product.name}" %>
        </h1>
      </th>
    </tr>

    <tr>
      <td style='width: 640px;'>
        <div>
          <div>
            <h2>
              <%= "#{@card.comment}"%>
            </h2>
          </div>
          <%= image_tag(@card.product.illustration, size: '640x480', class: 'img img-fluid')  if @card.product.illustration.present? %>
          <div>
            <h1>
              <%= "ткань: #{@card.fabric.title}" %>
            </h1>
            <h2>
              <%= @card.fabric.material %>
            </h2>
            <h2>
              <%= @card.fabric.description %>
            </h2>
          </div>
        </div>
      </td>

      <td style='width: 320px;'>
        <div>
          <%= image_tag(@card.fabric.illustration, size: '480x640', class: 'img img-fluid') if @card.fabric.illustration.present? %>
          <div>
            <h2>
              <strong>мерки</strong>
            </h2>
            <% @card.order_measures.each do |order_measure| %>
              <div>
                <h2>
                  <%= "#{[order_measure.measure.tag, ":", order_measure.value].join}" %>
                </h2>
              </div>
            <% end%>
          </div>
        </div>
      </td>
    </tr>
  </table>
</div>

app/views/cards/wicked_pdf.html.erb
<style>
table, th, td {
  border-collapse: collapse;
  vertical-align: baseline;
  text-align: left;
  vertical-align: top;
  text-align-last: justify;
}
th, td {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 8px;
  padding-right: 8px;
  vertical-align: baseline;
  text-align: left;
  vertical-align: top;
}
</style>

<div>
  <table style='width: 980px; height: 1080px; width: 100%;'>
    <tr style='height: 24px; width: 100%;'>
      <th>
        <div>
          <div style='flex-direction: row' >
            <h2>
              <%= "##{@card.idx}" %>
              <%= "#{@card.customer.nickname}" %>
            </h2>
          </div>
        </div>
      </th>
      <th>
        <h1>
          <%= "#{@card.product.name}" %>
        </h1>
      </th>
    </tr>

    <tr style='width: 100%; max-height: 640px;'>
      <td>
        <div>
          <%= wicked_pdf_image_tag(url_for(@card.product.illustration),
                                   size: '640x480',
                                   class: 'img img-fluid')  if @card.product.illustration.attached? %>
          <div>
            <strong>
              <%= @card.comment.gsub(/\n/, '<br/>').html_safe %>
            </strong>
          </div>
          <div>
            <h1>
              <%= "ткань: #{@card.fabric.title}" %>
            </h1>
            <h2>
              <%= @card.fabric.material %>
            </h2>
            <h2>
              <%= @card.fabric.description %>
            </h2>
          </div>
        </div>
      </td>

      <td>
        <div>
          <%= wicked_pdf_image_tag(url_for(@card.fabric.illustration),
                                   size: '480x640',
                                   class: 'img img-fluid') if @card.fabric.illustration.attached? %>
          <div>
            <h2>
              <strong>мерки</strong>
            </h2>
            <div>
              <h4>
                <%= @card.notes.gsub(/\n/, '<br/>').html_safe %>
              </h4>
            </div>
            <% @card.order_measures.each do |order_measure| %>
              <div>
                <h2>
                  <%= "#{[order_measure.measure.tag, ":", order_measure.value].join}" %>
                </h2>
              </div>
            <% end%>
          </div>
        </div>
      </td>
    </tr>
  </table>
</div>